openapi: 3.0.0
info:
  title: Hospital Backend
  version: 1.0.0
  description: This is a sample server for hospital studies backend.

tags:
  - name: bills
    description: Operations about bills
  
paths:
  /api/bills:
    get:
      tags:
        - bills
      summary: Get all bills
      operationId: getBills
      responses:
        '200':
          description: A list of bills
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bill'
    post:
      tags:
        - bills
      summary: Add a new bill
      operationId: addBill
      requestBody:
        description: Bill object that needs to be added
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                patient_id:
                  type: integer
                  required: true
                amount:
                  type: number
                  required: true
                date:
                  type: string
                  format: date
                  required: true
                status: 
                  type: string
                  required: true
                  enum: [paid, unpaid, canceled]
                study_id:
                  type: integer
                  required: true
      responses:
        '200':
          description: Bill added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
  /api/bills/{billId}:
    get:
      tags:
        - bills
      summary: Get a bill by ID
      operationId: getBill
      parameters:
        - name: billId
          in: path
          description: ID of bill to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A bill
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
    put:
      tags:
        - bills
      summary: Update a bill
      operationId: updateBill
      parameters:
        - name: billId
          in: path
          description: ID of bill to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Bill object that needs to be updated
        required: true
        content:
          application/json:
            schema:
                patient_id:
                  type: integer
                  required: true
                amount:
                  type: number
                  required: true
                date:
                  type: string
                  format: date
                  required: true
                status: 
                  type: string
                  required: true
                  enum: [paid, unpaid, canceled]
                study_id:
                  type: integer
                  required: true
      responses:
        '200':
          description: Bill updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
    delete:
      tags:
        - bills
      summary: Delete a bill
      operationId: deleteBill
      parameters:
        - name: billId
          in: path
          description:
  /api/bills/patient/{patientId}:
    get:
      tags:
        - bills
      summary: Get all bills of a patient
      operationId: getBillsByPatient
      parameters:
        - name: patientId
          in: path
          description: ID of patient to return bills
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A list of bills
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bill'
  /api/bills/patient/dni/{patientDni}:
    get:
      tags:
        - bills
      summary: Get all bills of a patient by DNI
      operationId: getBillsByPatientDni
      parameters:
        - name: patientDni
          in: path
          description: DNI of patient to return bills
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of bills
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bill'

components:
  schemas:
    Bill:
      type: object
      properties:
        id:
          type: integer
          format: int64
        patient_id:
          type: integer
          format: int64
        amount:
          type: number
        date:
          type: string
          format: date
        status:
          type: string
          enum: [paid, unpaid, canceled]
        study_id:
          type: integer
          format: int64