openapi: 3.0.0
info:
  title: Hospital Backend
  version: 1.0.0
  description: This is a sample server for hospital studies backend.

tags:
  - name: users
    description: Operations about users

paths:
  /api/session/me:
    get:
      tags:
        - users
      summary: Get user information
      operationId: getUser
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: integer
                  username:
                    type: string
                  email:
                    type: string
  /api/session/register:
    post:
      tags:
        - users
      summary: Register a new user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string
                example: User registered successfully
  /api/session/login:
    post:
      tags:
        - users
      summary: Login a user
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User logged in successfully
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      _id:
                        type: integer
                      name:
                        type: string
                      email:
                        type: string
                      role: 
                        type: string
  /api/session/logout:
    post:
      tags:
        - users
      summary: Logout a user
      operationId: logoutUser
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: User logged out successfully